### ISSUE TITLE
Does not seem to work with non-base branch

### ISSUE THREAD

**Issue by alllex** [paramt/url-checker#10]
I tried running this workflow on a non-base branch and it does not seem to see the content of the files in the branch.
I can only assume that it runs on a base branch regardless where the action has been dispatched.

I was trying to check if it will actually fail the build if there is broken link. But I was not able to do that, because the broken link (returns 404) is not even shown in the list of checked links.

**Comment by paramt** [comment]
Solved in v0.3.0 by #12 

Add this in your YAML: 
```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
```
You can then change `main` to any branch you'd like
